### ISSUE TITLE
Voxel terrain suggestions

### ISSUE THREAD

**Issue by luboslenco** [armory3d/voxel_world#6]

**Comment by jreach-dev** [comment]
@zauberparacelsus

You don't need a math degree. I taught myself everything I needed to know. I struggled in all the same areas you mentioned.

**Comment by jreach-dev** [comment]
Voxel Terrain Progress: Linear Octree report 2

Here is my current progress. I now have the ability to 'carve' my octree. Since subdivision only needs to happen near the carving it allows for much more efficient storage than typical voxels.

![carve_a](https://user-images.githubusercontent.com/31992088/40852574-d7f21100-6598-11e8-9587-a48873dfd842.PNG)
![carve_b](https://user-images.githubusercontent.com/31992088/40852575-d7fe4704-6598-11e8-8a58-46b3a7276407.PNG)
![carve_c](https://user-images.githubusercontent.com/31992088/40852576-d8118706-6598-11e8-9117-ebbef6081fbf.PNG)
![carve_d](https://user-images.githubusercontent.com/31992088/40852577-d81ee798-6598-11e8-812f-8740fd74938d.PNG)

Feel free to give any feedback as this will be considered during development!

**Comment by zauberparacelsus** [comment]
Does *carving* refer to just cutting out blocks from the terrain, or is it something else?

**Comment by jreach-dev** [comment]
Yea, what is the normal term? Basically I chose what level of the octree to 'dig' or 'carve'. The higher the level the smaller the edit.

**Comment by zauberparacelsus** [comment]
@ubaldy If you want to add me on Discord, I'm in the Godot server.  I'd add you from there, but there's apparently two of them O.o

**Comment by zauberparacelsus** [comment]
@ubaldy Incorporating Tessellation into the voxel terrain would be useful for adding detail without adding extra levels to the octree.

Example of voxel terrain with tessellation here: https://www.youtube.com/watch?v=P4R_2FQ-BJ0
